<?php
return [
    [
        "title" => "Casa Verde",
        "room_number" => 4,
        "bed_number" => 2,
        "bathroom_number" => 2,
        "surface_sqm" => 90,
        "full_address" => "Via Appia Nuova 123, Roma",
        "image" => "",
        "is_visible" => True,
        "latitude" => "41.867684",
        "longitude" => "12.537237",
        "user_id" => 1,
    ],
    [
        "title" => "Lolf al centro",
        "room_number" => 3,
        "bed_number" => 1,
        "bathroom_number" => 1,
        "surface_sqm" => 50,
        "full_address" => "Via Larga 2, Firenze",
        "image" => "",
        "is_visible" => False,
        "latitude" => "43.773266",
        "longitude" => "11.255865",
        "user_id" => 1,
    ],
    [
        "title" => "Vista mare",
        "room_number" => 2,
        "bed_number" => 1,
        "bathroom_number" => 1,
        "surface_sqm" => 60,
        "full_address" => "Corso Vittorio Emanuele 9, Napoli",
        "image" => "",
        "is_visible" => True,
        "latitude" => "40.837262",
        "longitude" => "14.250192",
        "user_id" => 1,
    ],
    [
        "title" => "Appartamento sul parco",
        "room_number" => 5,
        "bed_number" => 3,
        "bathroom_number" => 2,
        "surface_sqm" => 100,
        "full_address" => "Piazza del Popolo 1, Roma",
        "image" => "",
        "is_visible" => False,
        "latitude" => "41.910853",
        "longitude" => "12.476163",
        "user_id" => 1,
    ],
    [
        "title" => "La mansarda romantica",
        "room_number" => 6,
        "bed_number" => 2,
        "bathroom_number" => 2,
        "surface_sqm" => 110,
        "full_address" => "Via dei Fori Imperiali 1, Roma",
        "image" => "",
        "is_visible" => True,
        "latitude" => "41.892487",
        "longitude" => "12.485044",
        "user_id" => 1,
    ],
    [
        "title" => "Moderno bilocale",
        "room_number" => 3,
        "bed_number" => 2,
        "bathroom_number" => 1,
        "surface_sqm" => 70,
        "full_address" => "Piazza San Marco 1, Venezia",
        "image" => "",
        "is_visible" => True,
        "latitude" => "45.434336",
        "longitude" => "12.338784",
        "user_id" => 1,
    ],
    [
        "title" => "Casa accogliente",
        "room_number" => 4,
        "bed_number" => 3,
        "bathroom_number" => 2,
        "surface_sqm" => 80,
        "full_address" => "Piazza della Signoria 1, Firenze",
        "image" => "",
        "is_visible" => True,
        "latitude" => "43.769671",
        "longitude" => "11.255260",
        "user_id" => 1,
    ],
    [
        "title" => "Attico con terrazza panoramica",
        "room_number" => 2,
        "bed_number" => 1,
        "bathroom_number" => 1,
        "surface_sqm" => 60,
        "full_address" => "Via del Corso 10, Roma",
        "image" => "",
        "is_visible" => True,
        "latitude" => "41.902604",
        "longitude" => "12.481119",
        "user_id" => 1,
    ],
    [
        "title" => "Appartamento al mare",
        "room_number" => 7,
        "bed_number" => 3,
        "bathroom_number" => 3,
        "surface_sqm" => 120,
        "full_address" => "Via Nazionale 2, Roma",
        "image" => "",
        "is_visible" => True,
        "latitude" => "41.900031",
        "longitude" => "12.494999",
        "user_id" => 1,
    ],
    [
        "title" => "La casa dei sogni",
        "room_number" => 5,
        "bed_number" => 2,
        "bathroom_number" => 2,
        "surface_sqm" => 90,
        "full_address" => "Piazza dei Miracoli 1, Pisa",
        "image" => "",
        "is_visible" => True,
        "latitude" => "43.722952",
        "longitude" => "10.396597",
        "user_id" => 1,
    ],
    [
        "title" => "Appartamento di charme",
        "room_number" => 2,
        "bed_number" => 1,
        "bathroom_number" => 1,
        "surface_sqm" => 45,
        "full_address" => "Via Monte Napoleone 1, Milano",
        "image" => "",
        "is_visible" => True,
        "latitude" => "45.467523",
        "longitude" => "9.195637",
        "user_id" => 1,
    ],
    [
        "title" => "Casa vacanze tranquilla",
        "room_number" => 4,
        "bed_number" => 3,
        "bathroom_number" => 2,
        "surface_sqm" => 80,
        "full_address" => "Via Condotti 2, Roma",
        "image" => "",
        "is_visible" => True,
        "latitude" => "41.906593",
        "longitude" => "12.480382",
        "user_id" => 1,
    ],
    [
        "title" => "Casa vacanze tranquilla",
        "room_number" => 4,
        "bed_number" => 2,
        "bathroom_number" => 2,
        "surface_sqm" => 80,
        "full_address" => "Via Alessandro Manzoni, 1, 20123 Milano MI",
        "image" => "",
        "is_visible" => True,
        "latitude" => "45.467423",
        "longitude" => "9.194136",
        "user_id" => 1,
    ],
    [
        "title" => "Luminoso trilocale",
        "room_number" => 3,
        "bed_number" => 1,
        "bathroom_number" => 1,
        "surface_sqm" => 60,
        "full_address" => "Via dei Mille, 9, 00185 Roma RM",
        "image" => "",
        "is_visible" => True,
        "latitude" => "41.903930",
        "longitude" => "12.499248",
        "user_id" => 1,
    ],
    [
        "title" => "Appartamento in centro storico",
        "room_number" => 5,
        "bed_number" => 3,
        "bathroom_number" => 3,
        "surface_sqm" => 120,
        "full_address" => "Via Santa Margherita Ligure, 15, 00122 Cagliari CA",
        "image" => "",
        "is_visible" => True,
        "latitude" => "39.252336",
        "longitude" => "9.138058",
        "user_id" => 1,
    ],
    [
        "title" => "Bilocale moderno e funzionale",
        "room_number" => 2,
        "bed_number" => 1,
        "bathroom_number" => 2,
        "surface_sqm" => 45,
        "full_address" => "Via Francesco Crispi, 3, 90100 Palermo PA",
        "image" => "",
        "is_visible" => True,
        "latitude" => "38.118047",
        "longitude" => "13.361204",
        "user_id" => 1,
    ],
    [
        "title" => "Charme e design in città",
        "room_number" => 7,
        "bed_number" => 2,
        "bathroom_number" => 3,
        "surface_sqm" => 100,
        "full_address" => "Via Nazionale, 157, 00184 Roma RM",
        "image" => "",
        "is_visible" => True,
        "latitude" => "41.897889",
        "longitude" => "12.494248",
        "user_id" => 1,
    ],
    [
        "title" => "Suite deliziosa",
        "room_number" => 4,
        "bed_number" => 2,
        "bathroom_number" => 1,
        "surface_sqm" => 70,
        "full_address" => "Via Tornabuoni, 19, 50123 Firenze FI",
        "image" => "",
        "is_visible" => True,
        "latitude" => "43.771554",
        "longitude" => "11.253132",
        "user_id" => 1,
    ],
    [
        "title" => "Lussuoso attico con piscina",
        "room_number" => 6,
        "bed_number" => 3,
        "bathroom_number" => 3,
        "surface_sqm" => 115,
        "full_address" => "Via Carlo Goldoni, 2, 20129 Milano MI",
        "image" => "",
        "is_visible" => True,
        "latitude" => "45.463385",
        "longitude" => "9.200728",
        "user_id" => 1,
    ],
    [
        "title" => "Ampio trilocale con doppio servizio",
        "room_number" => 3,
        "bed_number" => 1,
        "bathroom_number" => 1,
        "surface_sqm" => 55,
        "full_address" => "Via Dante Alighieri, 37, 43121 Parma PR",
        "image" => "",
        "is_visible" => True,
        "latitude" => "44.803814",
        "longitude" => "10.327207",
        "user_id" => 1,
    ],
    [
        "title" => "Appartamento panoramico con giardino",
        "room_number" => 3,
        "bed_number" => 2,
        "bathroom_number" => 2,
        "surface_sqm" => 75,
        "full_address" => "Piazza Vittorio Veneto, 6, 10124 Torino TO",
        "image" => "",
        "is_visible" => True,
        "latitude" => "45.068645",
        "longitude" => "7.682506",
        "user_id" => 1,
    ],
];
