<?php
return [
    [
        "title" => "Appartamento 1",
        "room_number" => 1,
        "bed_number" => 3,
        "bathroom_number" => 2,
        "surface_sqm" => 90,
        "full_address" => "Via Roma 1, 00100 Roma",
        "image" => "",
        "is_visible" => True,
        "user_id" => 1,
    ],
    [
        "title" => "Appartamento 2",
        "room_number" => 2,
        "bed_number" => 2,
        "bathroom_number" => 1,
        "surface_sqm" => 70,
        "full_address" => "Via Roma 2, 00100 Roma",
        "image" => "",
        "is_visible" => False,
        "user_id" => 1,
    ],
    [
        "title" => "Appartamento 3",
        "room_number" => 7,
        "bed_number" => 3,
        "bathroom_number" => 2,
        "surface_sqm" => 80,
        "full_address" => "Via Nazionale 3, 00184 Roma",
        "image" => "",
        "is_visible" => True,
        "user_id" => 1,
    ],
    [
        "title" => "Appartamento 4",
        "room_number" => 3,
        "bed_number" => 1,
        "bathroom_number" => 1,
        "surface_sqm" => 60,
        "full_address" => "Via del Corso 4, 00186 Roma",
        "image" => "",
        "is_visible" => False,
        "user_id" => 1,
    ],
    [
        "title" => "Appartamento 30",
        "room_number" => 2,
        "bed_number" => 1,
        "bathroom_number" => 1,
        "surface_sqm" => 50,
        "full_address" => "Via Appia Nuova 30, 00179 Roma",
        "image" => "",
        "is_visible" => True,
        "user_id" => 1,
    ],
    [
        "title" => "Luminoso appartamento al centro",
        "room_number" => 5,
        "bed_number" => 2,
        "bathroom_number" => 1,
        "surface_sqm" => 70,
        "full_address" => "Piazza del Popolo 12, 00187 Roma",
        "image" => "",
        "is_visible" => True,
        "user_id" => 1,
    ],
    [
        "title" => "Appartamento con terrazza",
        "room_number" => 2,
        "bed_number" => 3,
        "bathroom_number" => 2,
        "surface_sqm" => 90,
        "full_address" => "Viale Trastevere 45, 00153 Roma",
        "image" => "",
        "is_visible" => True,
        "user_id" => 1,
    ],
    [
        "title" => "Appartamento in zona tranquilla",
        "room_number" => 2,
        "bed_number" => 1,
        "bathroom_number" => 1,
        "surface_sqm" => 60,
        "full_address" => "Via Flaminia Vecchia 111, 00196 Roma",
        "image" => "",
        "is_visible" => True,
        "user_id" => 1,
    ],
    [
        "title" => "Elegante appartamento nel centro storico",
        "room_number" => 4,
        "bed_number" => 2,
        "bathroom_number" => 2,
        "surface_sqm" => 80,
        "full_address" => "Piazza Navona 33, 00186 Roma",
        "image" => "",
        "is_visible" => True,
        "user_id" => 1,
    ],
    [
        "title" => "Appartamento con vista sulla città",
        "room_number" => 1,
        "bed_number" => 2,
        "bathroom_number" => 2,
        "surface_sqm" => 70,
        "full_address" => "Viale dei Colli Portuensi 30, 00151 Roma",
        "image" => "",
        "is_visible" => True,
        "user_id" => 1,
    ]
];
